version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx/beautymed/client
    ports:
      # Nuxt port
      - 8081:81
    links:
      - node

  # Node container
  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/client

  # Node command line container
  node-cli:
    build:
      context: docker/node-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/client
    tty: true
